### chessboard pattern
Write a function that returns a chessboard pattern ("B" for black squares, "W" for white squares). The function takes a number N as input and generates the corresponding board.

Example:
- Input: 5
- Output: 
- WBWBW
- BWBWB
- WBWBW
- BWBWB
- WBWBW

In [7]:
class Solution():
    def chessboardPattern(self,n):
        k = n // 2
        if n % 2 == 0 :
            line = ['W','B'] * k
            result = [line, line[::-1]] * k
        else:
            line1 = ['W','B'] * k +['W']
            line2 = ['B','W'] * k +['B']
            result = [line1, line2] * k + [line1]
        return result
            

n = 5
example = Solution()
example.chessboardPattern(n)

[['W', 'B', 'W', 'B', 'W'],
 ['B', 'W', 'B', 'W', 'B'],
 ['W', 'B', 'W', 'B', 'W'],
 ['B', 'W', 'B', 'W', 'B'],
 ['W', 'B', 'W', 'B', 'W']]

In [26]:
def get_chessboard(dim):
    chessboard = [[None for i in range(dim)] for j in range(dim)]
    
    for i in range(dim * dim):
        # print(i)
        m, n = divmod(i, dim)
        # print(m,n)
        
        if (m + n) % 2:
            chessboard[m][n] = 'B'
        else:
            chessboard[m][n] = 'W'
    
    return chessboard
n = 5
get_chessboard(n)

[['W', 'B', 'W', 'B', 'W'],
 ['B', 'W', 'B', 'W', 'B'],
 ['W', 'B', 'W', 'B', 'W'],
 ['B', 'W', 'B', 'W', 'B'],
 ['W', 'B', 'W', 'B', 'W']]

In [21]:
import numpy as np
  
# function to print Checkerboard pattern
def printcheckboard(n):
      
    print("Checkerboard pattern:")
  
    # create a n * n matrix
    x = np.zeros((n, n), dtype= int)
  
    # fill with 1 the alternate rows and columns
    x[1::2, ::2] = 1

    x[::2, 1::2] = 1

      
    # print the pattern
    for i in range(n):
        for j in range(n):
            print(x[i][j], end =" ") 
        print() 
printcheckboard(5)

Checkerboard pattern:
0 1 0 1 0 
1 0 1 0 1 
0 1 0 1 0 
1 0 1 0 1 
0 1 0 1 0 


In [20]:
import numpy as np
def printcheckboard(n):
    final = []
    for i in range(n):
        final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
    print(np.array(final))
  
  
# driver code
n = 8
printcheckboard(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
